# Generated by Django 4.2.11 on 2024-05-04 18:21

import app.models.base_models.mixins
import app.models.mappings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mappings',
            fields=[
                ('id', models.UUIDField(default=app.models.base_models.mixins.UUIDGenerator.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('src_value', models.CharField(max_length=50, validators=[app.models.mappings.validate_alphanumeric], verbose_name='Source Value')),
                ('dst_value', models.CharField(max_length=50, validators=[app.models.mappings.validate_alphanumeric], verbose_name='Destination Value')),
                ('src_type', models.CharField(max_length=50, validators=[app.models.mappings.validate_alphanumeric], verbose_name='Source Type')),
                ('dst_type', models.CharField(max_length=50, validators=[app.models.mappings.validate_alphanumeric], verbose_name='Destination Type')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Data Mapping',
                'verbose_name_plural': 'Data Mappings',
            },
        ),
    ]
