# Generated by Django 4.2.11 on 2024-05-04 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_article_description_sizematrix_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.description', verbose_name='Product Description'),
        ),
    ]
