# Generated by Django 4.2.11 on 2024-05-05 12:33

import app.models.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_product_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_number',
            field=models.CharField(max_length=5, validators=[app.models.validators.validate_article], verbose_name='Article Structure Code'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_structure',
            field=models.CharField(max_length=20, verbose_name='Article Structure Code'),
        ),
        migrations.AlterField(
            model_name='sizematrix',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[app.models.validators.validate_alphanumeric], verbose_name='Size Group Code | Size'),
        ),
    ]
