# Generated by Django 4.2.11 on 2024-05-05 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_article_article_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizematrix',
            name='size_name',
        ),
    ]
