# Generated by Django 4.2.11 on 2024-05-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_sizematrix_size_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_rate',
            field=models.CharField(max_length=4, verbose_name='Discount Rate'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_buy_gross',
            field=models.CharField(max_length=10, verbose_name='Gross Buying Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_buy_net',
            field=models.CharField(max_length=10, verbose_name='Net Buying Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_sell',
            field=models.CharField(max_length=10, verbose_name='Selling Price'),
        ),
    ]
