# Generated by Django 4.2.11 on 2024-05-05 12:56

import app.models.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_product_discount_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizematrix',
            name='size_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Size Name'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_number',
            field=models.CharField(max_length=5, validators=[app.models.validators.validate_article], verbose_name='Article Number'),
        ),
    ]
