# Generated by Django 4.2.11 on 2024-05-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_sizematrix_size_name_alter_article_article_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='color',
            field=models.CharField(max_length=20, verbose_name='Color Name'),
        ),
    ]
